---
abstract: 'Dancer2 colored console logger.'
author:
  - 'BURNERSK <burnersk@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Logger-Console-Colored
no_index:
  directory:
    - example
    - t
provides:
  Dancer2::Logger::Console::Colored:
    file: lib/Dancer2/Logger/Console/Colored.pm
requires:
  Dancer2::Core::Types: '0'
  Dancer2::Logger::Console: '0'
  Moo: '0'
  Term::ANSIColor: '0'
  perl: '5.013002'
resources:
  bugtracker: https://github.com/burnersk/Dancer2-Logger-Console-Colored/issues
  homepage: https://github.com/burnersk/Dancer2-Logger-Console-Colored
  repository: https://github.com/burnersk/Dancer2-Logger-Console-Colored.git
version: '0.001'
x_contributors:
  - 'BURNERSK <burnersk@cpan.org>'
